du:
  id: 1
  name: "DU-UE-Simulator"
  cucp_address: "127.0.0.1"
  cucp_port: 38472
  local_address: "127.0.0.1"
  local_port: 38473
  plmn:
    mcc: "999"
    mnc: "70"
  cell:
    pci: 1
    tac: "000001"

ue:
  nue: 2
  msin: "0000000001"
  supi: "208930000000001"
  suci: "imsi-99970-0000000001"
  key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
  opc: "E8ED289DEBA952E4283B54E88E6183CA"
  amf: "8000"
  plmn:
    mcc: "999"
    mnc: "70"
  events:
    - rrc_setup
    - registration
    - pdu_esta
    - handover


#TODO: instead of hard code the events (registration, pdu session, handover...) of UE
# you should defind the list of event in config files or with command line!!!
